site_name: gator Documentation
site_url: https://wayfair-incubator.github.io/gator/
repo_url: https://github.com/wayfair-incubator/gator/
repo_name: wayfair-incubator/gator
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "restructured-text"
          rendering:
            heading_level: 3
            show_root_heading: True
            show_source: False
            show_root_full_path: False
extra_css:
  - css/mkdocstrings.css
extra:
  version:
    provider: mike
